BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(39);

CREATE TABLE public.api_surface_disposable_table(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
SELECT ok((SELECT relrowsecurity FROM pg_catalog.pg_class WHERE oid='public.api_surface_disposable_table'::regclass),'new public table receives RLS');
SELECT ok(NOT has_table_privilege('anon','public.api_surface_disposable_table','SELECT,INSERT,UPDATE,DELETE'),'new table grants no anon DML');
SELECT ok(NOT has_table_privilege('authenticated','public.api_surface_disposable_table','SELECT,INSERT,UPDATE,DELETE'),'new table grants no authenticated DML');

CREATE FUNCTION public.api_surface_disposable_function() RETURNS integer
LANGUAGE sql IMMUTABLE AS 'SELECT 1';
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE p.oid='public.api_surface_disposable_function()'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'),'new routine grants no PUBLIC execute');
SELECT ok(NOT has_function_privilege('anon','public.api_surface_disposable_function()','EXECUTE'),'new routine grants no anon execute');
SELECT ok(NOT has_function_privilege('authenticated','public.api_surface_disposable_function()','EXECUTE'),'new routine grants no authenticated execute');

SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_event_trigger WHERE evtname='ensure_rls'),'ensure_rls exists');
SELECT is((SELECT evtenabled::text FROM pg_catalog.pg_event_trigger WHERE evtname='ensure_rls'),'O','ensure_rls is enabled');
SELECT is((SELECT evttags FROM pg_catalog.pg_event_trigger WHERE evtname='ensure_rls'),ARRAY['CREATE TABLE','CREATE TABLE AS','SELECT INTO']::text[],'ensure_rls targets table creation DDL');
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE p.oid='public.rls_auto_enable()'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'),'RLS event function is private from PUBLIC');
SELECT ok(NOT has_function_privilege('anon','public.rls_auto_enable()','EXECUTE'),'RLS event function is private from anon');
SELECT ok(NOT has_function_privilege('authenticated','public.rls_auto_enable()','EXECUTE'),'RLS event function is private from authenticated');
SELECT ok((SELECT prosecdef FROM pg_catalog.pg_proc WHERE oid='public.rls_auto_enable()'::regprocedure),'RLS event function remains security definer');
SELECT ok((SELECT proconfig @> ARRAY['search_path=pg_catalog'] FROM pg_catalog.pg_proc WHERE oid='public.rls_auto_enable()'::regprocedure),'RLS event function has controlled search path');

SELECT is(
  (SELECT array_agg(p.proname||'('||pg_catalog.pg_get_function_identity_arguments(p.oid)||')' ORDER BY p.proname,pg_catalog.pg_get_function_identity_arguments(p.oid))
   FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace
   WHERE n.nspname='public' AND has_function_privilege('anon',p.oid,'EXECUTE')),
  ARRAY['get_public_product_passport(p_public_slug text)','get_supplier_invite_metadata(p_token text)']::text[],
  'anonymous routine allowlist is exact');

SELECT is(
  (SELECT array_agg(p.proname||'('||pg_catalog.pg_get_function_identity_arguments(p.oid)||')' ORDER BY p.proname,pg_catalog.pg_get_function_identity_arguments(p.oid))
   FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace
   WHERE n.nspname='public' AND has_function_privilege('authenticated',p.oid,'EXECUTE')),
  ARRAY[
    'cancel_evidence_upload_intent(p_evidence_id uuid)','create_certification_from_evidence(p_evidence_id uuid, p_name text, p_expiry_date date)',
    'create_evidence_upload_intent(p_lifecycle_stage_id uuid, p_document_type text, p_original_filename text, p_mime_type text, p_size_bytes bigint)',
    'create_organization_with_admin(organization_name text)','create_supplier_contact(p_supplier_id uuid, p_name text, p_email text)',
    'create_supplier_invite(p_supplier_id uuid, p_email text)','current_actor_can_read_evidence_object(p_bucket text, p_path text)',
    'current_actor_can_upload_evidence(p_lifecycle_stage_id uuid)','current_actor_is_active_supplier_for(p_supplier_id uuid)',
    'delete_supplier_contact(p_supplier_contact_id uuid)','finalize_evidence_upload(p_evidence_id uuid)',
    'get_evidence_download_target(p_evidence_id uuid)','get_my_organization_evidence(p_product_id uuid)',
    'get_my_supplier_access()','get_my_supplier_evidence_tasks()','get_product_passport_publication_state(p_product_id uuid)',
    'get_public_product_passport(p_public_slug text)','get_supplier_access_admin(p_supplier_id uuid)',
    'get_supplier_invite_metadata(p_token text)','has_org_role(target_organization_id uuid, allowed_roles text[])',
    'is_org_member(target_organization_id uuid)','publish_product_passport(p_product_id uuid)',
    'redeem_supplier_invite(p_token text)','review_evidence_upload(p_evidence_id uuid, p_decision text, p_rejection_reason text)',
    'revoke_certification(p_certification_id uuid)','revoke_supplier_access(p_access_membership_id uuid, p_reason text)',
    'revoke_supplier_invite(p_invitation_id uuid)','rotate_product_passport_slug(p_product_id uuid)',
    'unpublish_product_passport(p_product_id uuid)','update_supplier_contact(p_supplier_contact_id uuid, p_name text, p_email text)'
  ]::text[], 'authenticated routine allowlist is exact');

SELECT is((SELECT count(DISTINCT p.oid) FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE n.nspname='public' AND acl.grantee=0 AND acl.privilege_type='EXECUTE'),0::bigint,'PUBLIC executes no public-schema routine');
SELECT is((SELECT count(*) FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prosecdef AND has_function_privilege('anon',p.oid,'EXECUTE') AND p.proname NOT IN ('get_public_product_passport','get_supplier_invite_metadata')),0::bigint,'no private security definer is anonymous-callable');

SELECT is((SELECT count(*) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','f') AND has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE')),0::bigint,'anon has no public table DML');
SELECT ok((SELECT bool_and(NOT has_table_privilege('anon','public.'||t,'SELECT')) FROM unnest(ARRAY['organizations','organization_members','profiles','suppliers','supplier_contacts','supplier_invites','supplier_access_memberships','evidence_uploads','certifications','audit_logs','audit_events','digital_product_passports']) t),'anon cannot select sensitive tables');
SELECT ok((SELECT bool_and(NOT has_table_privilege('authenticated','public.'||t,'SELECT,INSERT,UPDATE,DELETE')) FROM unnest(ARRAY['brands','users','audit_events','supplier_contacts','supplier_invites','supplier_access_memberships','evidence_uploads','certifications','digital_product_passports']) t),'RPC/server-only tables deny authenticated direct access');
SELECT ok(has_table_privilege('authenticated','public.audit_logs','SELECT'),'authenticated retains scoped audit read');
SELECT ok(NOT has_table_privilege('authenticated','public.audit_logs','INSERT,UPDATE,DELETE'),'authenticated cannot mutate audit log');
SELECT ok(has_table_privilege('authenticated','public.profiles','SELECT,INSERT,UPDATE'),'profile onboarding privileges remain');
SELECT ok(NOT has_table_privilege('authenticated','public.profiles','DELETE'),'profiles cannot be client-deleted');
SELECT ok((SELECT NOT public FROM storage.buckets WHERE id='compliance_docs'),'compliance bucket is private');
SELECT is((SELECT count(*) FROM pg_catalog.pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname IN ('compliance_docs_insert','compliance_docs_select')),2::bigint,'compliance object policies remain installed');
SELECT ok((SELECT relrowsecurity FROM pg_catalog.pg_class WHERE oid='public.supplier_access_memberships'::regclass),'supplier access membership has RLS');
SELECT is((SELECT r.rolname FROM pg_catalog.pg_event_trigger e JOIN pg_catalog.pg_proc p ON p.oid=e.evtfoid JOIN pg_catalog.pg_roles r ON r.oid=p.proowner WHERE e.evtname='ensure_rls'),'postgres','RLS event function is migration-owned');

SELECT ok(has_function_privilege('authenticated','public.create_organization_with_admin(text)','EXECUTE'),'organization onboarding RPC remains authorized');
SELECT ok(has_function_privilege('authenticated','public.create_supplier_invite(uuid,text)','EXECUTE'),'supplier RPC remains authorized');
SELECT ok(has_function_privilege('anon','public.get_public_product_passport(text)','EXECUTE'),'public DPP RPC remains authorized');
SELECT ok(has_function_privilege('authenticated','public.current_actor_can_upload_evidence(uuid)','EXECUTE'),'evidence authorization helper remains authorized');

SELECT ok(NOT EXISTS(SELECT 1 FROM pg_catalog.pg_default_acl d CROSS JOIN LATERAL aclexplode(coalesce(d.defaclacl,acldefault('r',d.defaclrole))) a JOIN pg_catalog.pg_roles g ON g.oid=a.grantee JOIN pg_catalog.pg_namespace n ON n.oid=d.defaclnamespace WHERE pg_get_userbyid(d.defaclrole)='postgres' AND n.nspname='public' AND d.defaclobjtype='r' AND g.rolname='anon' AND a.privilege_type IN ('SELECT','INSERT','UPDATE','DELETE')),'default tables deny anon DML');
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_catalog.pg_default_acl d CROSS JOIN LATERAL aclexplode(coalesce(d.defaclacl,acldefault('r',d.defaclrole))) a JOIN pg_catalog.pg_roles g ON g.oid=a.grantee JOIN pg_catalog.pg_namespace n ON n.oid=d.defaclnamespace WHERE pg_get_userbyid(d.defaclrole)='postgres' AND n.nspname='public' AND d.defaclobjtype='r' AND g.rolname='authenticated' AND a.privilege_type IN ('SELECT','INSERT','UPDATE','DELETE')),'default tables deny authenticated DML');
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE p.oid='public.api_surface_disposable_function()'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'),'default routines deny PUBLIC execute');
SELECT ok(NOT has_function_privilege('anon','public.api_surface_disposable_function()','EXECUTE'),'default routines deny anon execute');
SELECT ok(NOT has_function_privilege('authenticated','public.api_surface_disposable_function()','EXECUTE'),'default routines deny authenticated execute');
SELECT ok(NOT has_sequence_privilege('anon','public.api_surface_disposable_table_id_seq','USAGE') AND NOT has_sequence_privilege('authenticated','public.api_surface_disposable_table_id_seq','USAGE'),'default sequences deny client usage');

DROP TABLE public.api_surface_disposable_table;
DROP FUNCTION public.api_surface_disposable_function();
SELECT * FROM finish();
ROLLBACK;
