import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { AlertTriangle, ArrowLeft, CheckCircle2, ExternalLink, Pencil, Plus, Save, Trash2 } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
import { usePermissions } from "../lib/auth/usePermissions";
import { formatOperationalState } from "../lib/readiness";
import { blockerDestination, certificationLabel, dimensionValue, evidenceLabel, isWorkspaceReadOnly, materialComposition, metricValue, parseProductWorkspace, type ProductWorkspace as Workspace } from "../lib/productWorkspace";

export function ProductWorkspace() {
  const [,params]=useRoute("/products/:productId"); const productId=params?.productId ?? "";
  const { canEdit }=usePermissions(); const [data,setData]=useState<Workspace|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [editing,setEditing]=useState(false); const [productForm,setProductForm]=useState({name:"",sku:"",season:""});
  const [materialForm,setMaterialForm]=useState({material_name:"",composition_percentage:"",certification_required:false}); const [working,setWorking]=useState(false);
  async function load(){ if(!supabase)return; setLoading(true); const {data:value,error:e}=await (supabase.rpc as any)("get_product_workspace",{p_product_id:productId}); if(e||!value){setError("Product not found or access denied.");setData(null);}else{const parsed=parseProductWorkspace(value);setData(parsed);setProductForm({name:parsed.product.name,sku:parsed.product.sku??"",season:parsed.product.season??""});setError(null);}setLoading(false); }
  useEffect(()=>{void load();},[productId]);
  async function saveProduct(){if(!supabase)return;setWorking(true);const {error:e}=await (supabase.rpc as any)("update_product_metadata",{p_product_id:productId,p_name:productForm.name,p_sku:productForm.sku,p_season:productForm.season});setWorking(false);if(e)setError(e.message);else{setEditing(false);void load();}}
  async function addMaterial(e:React.FormEvent){e.preventDefault();if(!supabase)return;setWorking(true);const {error:e2}=await (supabase.rpc as any)("create_product_material",{p_product_id:productId,p_material_name:materialForm.material_name,p_composition_percentage:Number(materialForm.composition_percentage),p_certification_required:materialForm.certification_required});setWorking(false);if(e2)setError(e2.message);else{setMaterialForm({material_name:"",composition_percentage:"",certification_required:false});void load();}}
  async function removeMaterial(id:string){if(!supabase)return;setWorking(true);const {error:e}=await (supabase.rpc as any)("remove_product_material",{p_material_id:id});setWorking(false);if(e)setError(e.message);else void load();}
  if(loading)return <div className="p-8">Loading product workspace…</div>;
  if(error&&!data)return <div className="p-8 max-w-xl"><AlertTriangle className="text-amber-600 mb-3"/><h1 className="text-xl font-semibold">Product unavailable</h1><p className="text-muted-foreground mt-2">{error}</p><Link href="/products" className="text-primary inline-block mt-4">Back to Product Catalog</Link></div>;
  if(!data)return null;
  const readOnly=isWorkspaceReadOnly(data.product.status,canEdit); const composition=materialComposition(data.materials); const readiness=data.readiness;
  return <div className="p-6 md:p-8 max-w-6xl mx-auto space-y-6">
    <Link href="/products" className="text-sm text-muted-foreground flex items-center gap-1"><ArrowLeft className="w-4 h-4"/>Product Catalog</Link>
    {data.product.status==="archived"&&<div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-amber-800"><strong>Archived product</strong> — historical records remain viewable, but remediation is disabled.</div>}
    <header id="product-details" className="bg-card border rounded-xl p-6">
      <div className="flex justify-between gap-4">{editing?<div className="grid sm:grid-cols-3 gap-3 flex-1"><input aria-label="Product name" className="border rounded p-2" value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/><input aria-label="SKU" className="border rounded p-2" value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/><input aria-label="Season" className="border rounded p-2" value={productForm.season} onChange={e=>setProductForm({...productForm,season:e.target.value})}/></div>:<div><h1 className="text-2xl font-bold">{data.product.name}</h1><p className="text-muted-foreground">SKU: {data.product.sku||"No data"} · {data.product.season||"No season"} · {formatOperationalState(data.product.status)}</p></div>}
      {!readOnly&&(editing?<button disabled={working} onClick={saveProduct} className="text-primary flex gap-1"><Save className="w-4"/>Save</button>:<button onClick={()=>setEditing(true)} className="text-primary flex gap-1"><Pencil className="w-4"/>Edit</button>)}</div>
      {readiness?<div className="grid sm:grid-cols-3 gap-4 mt-6"><Stat value={`${readiness.overall_percent}%`} label="complete"/><Stat value={String(readiness.blocker_count)} label={`blocker${readiness.blocker_count===1?"":"s"}`}/><Stat value={formatOperationalState(readiness.dpp_state)} label="DPP state"/></div>:<p className="mt-5 text-muted-foreground">Readiness is unavailable for archived products.</p>}
    </header>
    {readiness&&<section className="grid lg:grid-cols-2 gap-6"><div className="bg-card border rounded-xl p-5"><h2 className="font-semibold mb-4">Readiness breakdown</h2><div className="space-y-3">{Object.entries(readiness.dimensions).map(([name,d])=><div key={name} className="flex justify-between border-b pb-2"><span>{formatOperationalState(name)}</span><strong>{dimensionValue(d)}</strong></div>)}</div></div>
    <div className="bg-card border-2 border-amber-200 rounded-xl p-5"><h2 className="font-semibold text-lg">What needs attention</h2>{!readiness.blockers.length?<p className="mt-4 text-muted-foreground">This product has no current readiness blockers.</p>:<div className="divide-y">{readiness.blockers.map(b=><article key={b} className="py-4"><h3 className="font-medium">{b}</h3><p className="text-sm text-muted-foreground mt-1">This current product record does not satisfy the readiness check.</p><a href={blockerDestination(b,productId)} className="text-sm text-primary inline-flex gap-1 mt-2">Resolve blocker <ExternalLink className="w-3"/></a></article>)}</div>}</div></section>}
    <section id="materials" className="bg-card border rounded-xl p-5"><div className="flex justify-between"><div><h2 className="font-semibold text-lg">Materials</h2><p className="text-sm text-muted-foreground">Recorded composition: {composition.total}%</p></div>{composition.invalid&&<span className="text-red-700 font-medium">Invalid: total exceeds 100%</span>}</div>
      {!data.materials.length?<p className="py-5 text-muted-foreground">No materials have been recorded.</p>:<div className="divide-y mt-3">{data.materials.map(m=><div key={m.id} className="py-3 flex justify-between"><span>{m.material_name}{m.certification_required&&<small className="ml-2 text-muted-foreground">Certification required</small>}</span><span className="flex gap-3"><strong>{m.composition_percentage}%</strong>{!readOnly&&<button disabled={working} aria-label={`Remove ${m.material_name}`} onClick={()=>removeMaterial(m.id)}><Trash2 className="w-4 text-red-600"/></button>}</span></div>)}{!composition.invalid&&composition.remainder>0&&<div className="py-3 flex justify-between text-amber-700"><span>Missing</span><strong>{composition.remainder}%</strong></div>}</div>}
      {!readOnly&&<form onSubmit={addMaterial} className="grid sm:grid-cols-4 gap-2 mt-4 border-t pt-4"><input required className="border rounded p-2" placeholder="Material name" value={materialForm.material_name} onChange={e=>setMaterialForm({...materialForm,material_name:e.target.value})}/><input required type="number" min="0.01" max="100" step="0.01" className="border rounded p-2" placeholder="Percentage" value={materialForm.composition_percentage} onChange={e=>setMaterialForm({...materialForm,composition_percentage:e.target.value})}/><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={materialForm.certification_required} onChange={e=>setMaterialForm({...materialForm,certification_required:e.target.checked})}/>Certification required</label><button disabled={working} className="bg-primary text-primary-foreground rounded p-2 flex justify-center gap-1"><Plus className="w-4"/>Add</button></form>}</section>
    <section className="bg-card border rounded-xl p-5"><div className="flex justify-between"><h2 className="font-semibold text-lg">Supply chain & evidence</h2><Link href={`/traceability?productId=${productId}`} className="text-primary text-sm">Open full traceability</Link></div>{!data.lifecycle.length?<p className="py-5 text-muted-foreground">No supply-chain stages have been added.</p>:<div className="divide-y mt-3">{data.lifecycle.map(s=><div key={s.id} className="py-3 grid sm:grid-cols-5 gap-2 text-sm"><strong>{s.stage_name}</strong><span>{s.supplier_name||"No supplier"}</span><span>CO₂: {metricValue(s.co2_impact_kg,"kg")}</span><span>Water: {metricValue(s.water_usage_l,"L")}</span><span className={s.evidence_state==="trusted"?"text-green-700":"text-amber-700"}>{evidenceLabel(s.evidence_state)}{s.flagged&&" · Flagged"}</span></div>)}</div>}</section>
    <section id="certifications" className="bg-card border rounded-xl p-5"><h2 className="font-semibold text-lg">Certifications</h2>{!data.certifications.length?<p className="py-5 text-muted-foreground">No evidence-backed certifications exist for this product.</p>:<div className="divide-y mt-3">{data.certifications.map(c=><div key={c.id} className="py-3 flex justify-between"><span>{c.name}</span><span>{certificationLabel(c)}{c.expiry_date&&` · expires ${c.expiry_date}`}</span></div>)}</div>}</section>
    <section className="bg-card border rounded-xl p-5 flex justify-between"><div><h2 className="font-semibold text-lg">Digital Product Passport</h2><p className="text-sm text-muted-foreground">{readiness?formatOperationalState(readiness.dpp_state):"Historical product"}. Internal readiness is not a legal-compliance determination.</p></div><Link href={`/passport?productId=${productId}`} className="text-primary">Open DPP</Link></section>
  </div>;
}
function Stat({value,label}:{value:string;label:string}){return <div className="bg-muted/50 rounded-lg p-4"><strong className="text-2xl">{value}</strong><p className="text-sm text-muted-foreground">{label}</p></div>}
